### ISSUE TITLE
리뷰 권한 부여

### ISSUE THREAD

**Issue by soohyuneeee** [she-s-thema/kkm_server#21]
우리 프로젝트 시스템 상 교환하는 약속 1개 다시 돌려주는 약속 1개 총 약속 두 개를 잡습니다.
거래 완료 표시를
_**약속 두 개가 끝나고 두 거래자 모두 거래 완료를 눌렀을 때**_
표시한다는 가정 하에
두 명 다 **Trade - trade_state에 완료**를 넣습니다.
그 다음 각각의 약속 아이디 두 개와 각각의 사용자 이름과 거래 테이블의 trade_state가 완료라면 
서로가 서로에게 리뷰권한을 줄 수 있게 하는것이 어떨까요?
리뷰 권한 테이블을 따로 만들고 다시.. 입렵받고... 있으면 리뷰 받고... 이런식으로...

**Comment by kimhyerin0909** [comment]
좋습니다
거래완료 하게 되면 바로 리뷰 권한을 줄 수 있게끔 하면 좋겠군요.
